name: Deploy APK to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload APK to S3
        uses: aws-actions/amazon-s3-deploy@v0.2.0
        with:
          bucket-name: my-bucket
          path-prefix: my-app
          region: us-east-1
          local-path: app/build/outputs/apk/debug/app-debug.apk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}      


    

